### ISSUE TITLE
Billing Policy Timeout needs to increase

### ISSUE THREAD

**Issue by mattdot** [microsoft/terraform-provider-power-platform#376]
Need to increase billing policy timeout.  3 minutes is not long enough for billing policies.  Recommend 15 minutes.

> powerplatform_billing_policy.test_policy: Still creating... [3m0s elapsed]
> ╷
> │ Error: Client error when creating powerplatform__billing_policy
> │ 
> │   with powerplatform_billing_policy.test_policy,
> │   on application_user.tf line 77, in resource "powerplatform_billing_policy" "test_policy":
> │   77: resource "powerplatform_billing_policy" "test_policy" {
> │ 
> │ timeout reached while waiting for billing policy to reach a terminal state
> │ (Enabled or Disabled)
> ╵
> Releasing state lock. This may take a few moments...

**Comment by rpothin** [comment]
Hi @mattdot,

I worked on the implementation of the timeout 😊

Question regarding the expected outcome for this issue: in general, with infrastructure as code deployment, how long waiting for the final status of the deployment of a resource is "too long"?

Regarding this specific resource - billing policy -, what is the equivalent of the SLA or SLO for the for the creation?
Because if for example the product team in charge of this capability - and the related API - says the creation should be completed under 10 minutes most of the time we should not have to go over that for the timeout, no?

I hope my point will not create confusion regarding what you are trying to achieve here.

Have a great day 😊

**Comment by mattdot** [comment]
We should consider using the standard timeout values from the provider sdk https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts

**Comment by rpothin** [comment]
Make sense, thank you very much for your answer @mattdot 😊
